### ISSUE TITLE
pipeline lacking code review

### ISSUE THREAD

**Issue by secknv** [ABC-COVID19/API-backend#19]
## Problem
Ao fazer commits para feature/xxx, o jenkins dá force merge para o develop o que implica:
1. Não há code review
2. Se eu tiver criado o meu feature/xx branch a partir de uma older version do develop, vai se perder code com o force merge

## Proposed Solution
Em fez de auto force merge dos feature/ branches podíamos ter um sistema onde se abriam PRs para o develop e o jenkins fazia build e deploy do develop quando eram aceites

**Comment by secknv** [comment]
# Proposed Flow

**Developer:**
1. Dev cria new branch from develop
2. add new features / code / etc
3. Push do novo branch para o repo
4. Abre PR
5. PR approved

**Jenkins:**

6. Jenkins detecta changes no develop
7. Jenkins faz build e deploy com opção de merge to master

**Comment by b4ld** [comment]
Pipeline completa.

Corre o **develop  a quando o PR aprovado:**

- Up version patch (version.txt) - pom é manage pelos developers

- Merge para master e deploy pra prod - same process as before

Note: Pipe corre sempre 2x, uma quando deteta Changes, e outra recursiva.
nesta ultima não é necessario qualquer acção
