### ISSUE TITLE
Criar draft e serviços core

### ISSUE THREAD

**Issue by alchimystic** [ABC-COVID19/API-backend#2]
O objectivo é definir o conjunto de serviços core do backend

**Comment by secknv** [comment]
Bom início:
1. Fetch articles do PubMed ([doc](https://docs.google.com/document/d/1ptniK1Ypugoaqu-ffg2E3hamylOn-_a1NnYSyJDgBV8/edit#heading=h.itp4k3wolme7))
2. User login
3. Parte privada:  
    * User pode escolher que artigos são displayed
    * User pode adicionar título, resumo e categoria em português
4. Parte pública que faz display dos artigos
